### ISSUE TITLE
MassAssignmentException (LogMessage model)

### ISSUE THREAD

**Issue by itpilotdk** [yoeriboven/laravel-log-db#2]
**This throws MassAssignmentException:**
 Log::channel('db')->error("Testerror", ['key' => $value]);

The model should only have id as guarded, or all the other fields should be fillable.?
 protected $guarded = ['id']; 

**Trace:**

Illuminate\Database\Eloquent\MassAssignmentException 

  Add [level] to fillable property to allow mass assignment on [Yoeriboven\LaravelLogDb\Models\LogMessage].

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:433
    429▕             // the model, and all others will just get ignored for security reasons.
    430▕             if ($this->isFillable($key)) {
    431▕                 $this->setAttribute($key, $value);
    432▕             } elseif ($totallyGuarded) {
  ➜ 433▕                 throw new MassAssignmentException(sprintf(
    434▕                     'Add [%s] to fillable property to allow mass assignment on [%s].',
    435▕                     $key, get_class($this)
    436▕                 ));
    437▕             }

**Comment by itpilotdk** [comment]
Temp fix:

Add "LogMessage::unguard();" to the boot method of AppServiceProvider.php in app/Providers.
Remember to import the class in use statement too.

**Comment by yoeriboven** [comment]
`LogMessage` is already unguarded [here](https://github.com/yoeriboven/laravel-log-db/blob/main/src/Models/LogMessage.php#L15).

I spoke with someone else who had the same issue. Turned out he had a bad installation. Could you check your vendor folder and see if the LogMessage model has the same `$guarded` property as [here](https://github.com/yoeriboven/laravel-log-db/blob/main/src/Models/LogMessage.php#L15)?

**Comment by JustonJ99** [comment]
> `LogMessage` is already unguarded [here](https://github.com/yoeriboven/laravel-log-db/blob/main/src/Models/LogMessage.php#L15).
> 
> I spoke with someone else who had the same issue. Turned out he had a bad installation. Could you check your vendor folder and see if the LogMessage model has the same `$guarded` property as [here](https://github.com/yoeriboven/laravel-log-db/blob/main/src/Models/LogMessage.php#L15)?

Hi, I got the same issue but I have to add guard attribute to model manually in vendor. The package does not add the guard attribute automatically,

**Comment by itpilotdk** [comment]
> `LogMessage` is already unguarded [here](https://github.com/yoeriboven/laravel-log-db/blob/main/src/Models/LogMessage.php#L15).
> 
> I spoke with someone else who had the same issue. Turned out he had a bad installation. Could you check your vendor folder and see if the LogMessage model has the same `$guarded` property as [here](https://github.com/yoeriboven/laravel-log-db/blob/main/src/Models/LogMessage.php#L15)?

The $guarded property didn't exist in my vendor folder no:) 

My composer downloaded the 1.0 tag, which has this issue:)
https://github.com/yoeriboven/laravel-log-db/blob/1.0/src/Models/LogMessage.php

![image](https://user-images.githubusercontent.com/88710986/193529866-b142df46-4e86-4f6f-a152-93b3caeeeaec.png)

**Comment by yoeriboven** [comment]
Whoops. I made a dumb mistake. I added the `$guarded` attribute but forgot to tag a new release. Install 1.0.1 and it should be fixed.

Fixed by 1.0.1
